language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - "nightly"
sudo: false
notifications:
  email:
    ervikrant06@gmail.com
install:
  - "pip install xmlvirshparser"
script:
  - xmlvirshparser virsh_-r_dumpxml_instance-000026a7
